---
title: "Differences Ongoing/Closed Projects"
draft: true
---

Here you can see the differences in Field Type between closed and ongoing projects:

```{r}
#| label: setup
#| include: false
library(tidyverse)
library(gt)
library(fs)

data <- dir_ls("data", glob = "*.csv") |> 
  read_csv(id = "Module", show_col_types = F) |>
  mutate(Module = fs::path_file(Module) |> path_ext_remove()) |>
  select(Module, `Field name`, starts_with("Field Type"))
```

```{r}
#| echo: false
#| output: asis 
diff <- data |>
  filter(`Field Type Closed` != `Field Type Ongoing`)

diff |>
  gt() |>
    tab_style( # Make "Mandatory" values red
      locations = list(cells_body(
        columns = `Field Type Closed`,
        rows = `Field Type Closed` == "Mandatory"
      ),cells_body(
        columns = `Field Type Ongoing`,
        rows = `Field Type Ongoing` == "Mandatory"
      )),
      style = list(cell_text(color = 'red'))
    ) |>
    tab_options(
      # table.width = pct(100), # give 100% width to table
      quarto.disable_processing = TRUE # prevent quarto from messing with gt table formatting
    ) |>
    opt_stylize(style = 1) |> # Striped look
    cols_align(
      align = "left",
      columns = everything()
    )
```

Differences in Mandatory fields between closed and ongoing projects:

```{r}
# Count per Module number of times Field Type Closed is Mandatory and Field Type Ongoing is Mandatory
data |>
  group_by(Module) |>
  summarise(
    `Mandatory Closed` = sum(`Field Type Closed` == "Mandatory"),
    `Mandatory Ongoing` = sum(`Field Type Ongoing` == "Mandatory")
  ) |>
  gt() |>
    tab_options(
      # table.width = pct(100), # give 100% width to table
      quarto.disable_processing = TRUE # prevent quarto from messing with gt table formatting
    ) |>
    opt_stylize(style = 1) |> # Striped look
    cols_align(
      align = "left",
      columns = everything()
    )
```